### ISSUE TITLE
Arquivo settings.json não encontrado

### ISSUE THREAD

**Issue by desestrutura** [juniorgasparotto/NubankCli#1]
Boa tarde!

Clonei o projeto e defini o alias como recomendado no readme, mas ao logar, é retornada uma exception:

Unhandled exception. System.IO.FileNotFoundException: The configuration file 'settings.json' was not found and is not optional. The physical path is 'C:\code\NubankCli\src\NubankCli\settings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at NubankCli.Core.DI.ConfigurationExtensions.AddConfiguration(IServiceCollection services, String configFolder, String settingsFileName) in C:\code\NubankCli\src\NubankCli.Core\DI\ConfigurationExtensions.cs:line 15
   at NubankCli.Program.<>c__DisplayClass0_0.<Main>b__0() in C:\code\NubankCli\src\NubankCli\Program.cs:line 27
   at SysCommand.ConsoleApp.App.RunApplication(Func`1 appFactory, Boolean breakEndLine)
   at NubankCli.Program.Main() in C:\code\NubankCli\src\NubankCli\Program.cs:line 21

**Comment by juniorgasparotto** [comment]
O arquivo de settings foi excluído por engano. tente novamente por favor.

Abs

**Comment by desestrutura** [comment]
Agora com o arquivo no repositório funcionou, obrigado!
